CREATE TABLE FEE_STUDENT (
ROLLNO VARCHAR(10), 
NAME VARCHAR(15), 
SEX VARCHAR(10), 
COURSE VARCHAR(15), 
FEE INT(10), 
PAID INT(10), 
DUE INT(10), 
ADDRESS VARCHAR(2000), 
CONTACT VARCHAR(12),
FIRST_INST INT(6),
SECOND_INST INT(6),
THIRD_INST INT(6),
MNAME VARCHAR(15),
LNAME VARCHAR(20), 
CONSTRAINT FEE_ACCOUNTANT_PK PRIMARY KEY (ROLLNO));
/

CREATE TABLE  FEE_ACCOUNTANT 
   (	ID INT(10), 
	NAME VARCHAR(200), 
	EMAIL VARCHAR(35), 
	PASSWORD VARCHAR(20), 
	ADDRESS VARCHAR(200), 
	CONTACT VARCHAR(12), 
	CONSTRAINT FEE_ACCOUNTANT_PK PRIMARY KEY (ID)
   )
/

